import { type Language } from "@/app/types";

export const LANGUAGES: Language[] = [
    { name: "Arabic (Generic)", code: "ar-XA" },
    { name: "Bengali (India)", code: "bn-IN" },
    { name: "Dutch (Belgium)", code: "nl-BE" },
    { name: "Dutch (Netherlands)", code: "nl-NL" },
    { name: "English (Australia)", code: "en-AU" },
    { name: "English (India)", code: "en-IN" },
    { name: "English (United Kingdom)", code: "en-GB" },
    { name: "English (United States)", code: "en-US" },
    { name: "French (Canada)", code: "fr-CA" },
    { name: "French (France)", code: "fr-FR" },
    { name: "German (Germany)", code: "de-DE" },
    { name: "Gujarati (India)", code: "gu-IN" },
    { name: "Hindi (India)", code: "hi-IN" },
    { name: "Indonesian (Indonesia)", code: "id-ID" },
    { name: "Italian (Italy)", code: "it-IT" },
    { name: "Japanese (Japan)", code: "ja-JP" },
    { name: "Kannada (India)", code: "kn-IN" },
    { name: "Korean (South Korea)", code: "ko-KR" },
    { name: "Malayalam (India)", code: "ml-IN" },
    { name: "Mandarin Chinese (China)", code: "cmn-CN" },
    { name: "Marathi (India)", code: "mr-IN" },
    { name: "Polish (Poland)", code: "pl-PL" },
    { name: "Portuguese (Brazil)", code: "pt-BR" },
    { name: "Russian (Russia)", code: "ru-RU" },
    { name: "Spanish (Spain)", code: "es-ES" },
    { name: "Spanish (United States)", code: "es-US" },
    { name: "Swahili (Kenya)", code: "sw-KE" },
    { name: "Tamil (India)", code: "ta-IN" },
    { name: "Telugu (India)", code: "te-IN" },
    { name: "Thai (Thailand)", code: "th-TH" },
    { name: "Turkish (Turkey)", code: "tr-TR" },
    { name: "Ukrainian (Ukraine)", code: "uk-UA" },
    { name: "Urdu (India)", code: "ur-IN" },
    { name: "Vietnamese (Vietnam)", code: "vi-VN" },
];
